/**
 * 与 `icons.js` 中 name 一一对应，统一使用 Element Plus 矢量图标（更清晰）。
 * 未映射的名称将回退到像素 SVG。
 */
import {
  Bell,
  Brush,
  Calendar,
  ChatDotRound,
  ChatLineRound,
  CircleClose,
  Clock,
  Coin,
  CollectionTag,
  Document,
  EditPen,
  Filter,
  FolderOpened,
  Goods,
  HomeFilled,
  InfoFilled,
  List,
  Location,
  Lock,
  MagicStick,
  Medal,
  Monitor,
  Notebook,
  Reading,
  School,
  Setting,
  TrendCharts,
  UploadFilled,
  User,
  UserFilled,
  TrophyBase,
  Promotion,
} from '@element-plus/icons-vue'

export const VECTOR_ICON_BY_NAME = {
  home: HomeFilled,
  folder: FolderOpened,
  study: Reading,
  spark: MagicStick,
  schedule: Calendar,
  map: Location,
  notice: Bell,
  plaza: ChatDotRound,
  market: Goods,
  messages: ChatLineRound,
  profile: UserFilled,
  settings: Setting,
  materials: Document,
  refine: Filter,
  questions: EditPen,
  notes: Notebook,
  todos: List,
  clock: Clock,
  practice: Medal,
  wrong: CircleClose,
  review: CollectionTag,
  report: TrendCharts,
  admin: Monitor,
  lock: Lock,
  user: User,
  bell: Bell,
  palette: Brush,
  database: Coin,
  info: InfoFilled,
  upload: UploadFilled,
  school: School,
  dino: TrophyBase,
  plane: Promotion,
}
